version: 2.1
orbs:
  azure-aks: circleci/azure-aks@0.3.0

jobs:
  # hello-job:
  #   docker:
  #     - image: alpine:3.13 #cimg/node:17.2.0 # the primary container, where your job's commands are run
  #       # auth:
  #       #   username: mydockerhub-user
  #       #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  #   steps:
  #     - checkout # check out the code in the project directory
  #     - run: echo "hello world" # run the `echo` command

workflows:
  # my-workflow:
  #   jobs:
  #     - hello-job
  

      
  example-workflow:
      jobs:
        - azure-aks/create-cluster:
            service-principal: AZURE_SP 
            create-resource-group: false 
            admin-username: ramonpizana 
            cluster-name: mycluster-circleci 
            resource-group: ramon-pizana 
            subscription: c4774376-bc4c-48e6-93eb-c0ac26c6345d 
            show-az-command: false 
            generate-ssh-keys: false 
            no-ssh-key: true 
            no-wait: false 
            skip-kubectl-install: false 
            client-secret: AZURE_SP_PASSWORD
            context: 
              - azvars

