apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: nodejs
  name: nodejs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
  name: nodejs
  namespace: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: rp00831866/nodejs-aks-app:8cab9fc22471c87083ab7fda4ddd9e7bc3a6a356
        name: nodejs-aks-app
        ports:
        - containerPort: 1337
          name: http
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Ingress
metadata:
  labels:
    app: nodejs
  name: nodejs
  namespace: nodejs
spec:
  ports:
  - port: 80
    targetPort: 1337
  selector:
    app: nodejs
  type: Ingress
